### ISSUE TITLE
repurpose Prefixes table as generic server info store

### ISSUE THREAD

**Issue by Foxite** [AlekEagle/dadbot#48]
The main thing I want to do today is allow server admins to opt out of the global sex alarm, because I consider it a privacy risk.

To do this I think it's best to add a command for server admins to change their optout status, and track it in the database.

We have a table that stores the prefixes of all servers. We could extend this table to track the optout status of each server. We'd have to add a column to a table with, I don't know but you do, potentially millions of records. This might put the database out of commission for a while. I don't know how long exactly, depends on your server's hardware.

Do you think this is a good idea?

An alternative is to add a new table just for this.

**Comment by WaviestBalloon** [comment]
> The main thing I want to do today is allow server admins to opt out of the global sex alarm, because I consider it a privacy risk.

Isn't the sex alarm only in Alek's server? I'm sure the bot is not invitable. Also not entirely sure how this is a "privacy risk", could you expand upon that more?

**Comment by Foxite** [comment]
The privacy risk isn't very big but it's still a risk to be leaking usernames from random discord users, especially since they removed discriminators.

The bot I'm talking about is the one that is invitable, it responds to the word "sex" being said in *any* server and sends the username to a channel in alek's server.

**Comment by WaviestBalloon** [comment]
> The bot I'm talking about is the one that is invitable, it responds to the word "sex" being said in _any_ server and sends the username to a channel in alek's server.

That channel is for people who say the keyword "sex" anywhere in Alex's server, I'm not sure where you got the idea of it doing it in any server and last time I checked, the sex alarm bot cannot be invited at all.

**Comment by Foxite** [comment]
As of this morning, the channel "dad-funny-word-alarm" covers every server, and it's performed by the main dad bot. At least it covers our private server. I did check.

**Comment by WaviestBalloon** [comment]
> As of this morning, the channel "dad-funny-word-alarm" covers every server, and it's performed by the main dad bot. At least it covers our private server. I did check.

Ah, this is a brand new feature that was just pushed recently today, I'll forward this issue to Danii right now

**Comment by AlekEagle** [comment]
First off, I'm glad you're bringing this up, first off, there's a pretty big chance that this will not be sticking around for too long, like many of the really idiotic features added to dad bot, this one was added last night in a sleep deprived haze. If it does stick around, one of the guaranteed changes is to use a user's display name instead of their username. Second, there will be a new flag added for the settings that will allow for easy toggling, using settings will allow for it to be toggled on a per user, channel, and server basis. Settings uses an extendable bitwise flag system to store binary options. If you don't think these proposed changes are sufficient or you have any additional ideas, questions, or comments, please let me know!

**Comment by Foxite** [comment]
That sounds much better than what I was planning! :D

**Comment by AlekEagle** [comment]
The Dad Bot Sex Alarm™ was officially completely removed as of commit fc14ccf3c07a5aee7df32b077e38b56771f356dd
